/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cat_system_MemoryService */

#ifndef _Included_com_cat_system_MemoryService
#define _Included_com_cat_system_MemoryService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cat_system_MemoryService
 * Method:    getMemoryUsage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cat_system_MemoryService_getMemoryUsage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
